functions/urls.py
from django.urls import path
from . import views

# [코드 작성] 'functions'앱 이름 설정하기
app_name = "functions"

# 'path'의 'name' 속성으로 url의 별칭을 지정하기
urlpatterns = [
    path('index/', views.index, name="index"),
    path('image/', views.image, name="image"),
    path('lucky/', views.lucky, name="lucky"),
    path('birthday/', views.birthday, name="birthday"),
    path('ranking/', views.ranking, name="ranking"),
    # [코드 작성] 문자열 인자 전달하기
    path('language/<str:name>/', views.language, name="language")
]

games/urls.py
from django.urls import path
from . import views

app_name = "games"

urlpatterns = [
    path('rsp/', views.rsp, name="rsp"),
    path('rsp/<str:pick>', views.result, name="result"),
    path('reset/', views.reset, name="reset"),
]

intro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('functions.urls')),
    # [코드 작성] 'games'앱의 'urls.py' 포함시키기
    path('games/', include('games.urls')),
]

games/models.py
from django.db import models

# Create your models here.

functions/views.py
from django.shortcuts import render
# [코드 작성] 'random'모듈 가져오기
from random import *
# [코드 작성] 'datetime'모듈 가져오기
import datetime

# Create your views here.
def index(request):
    return render(request, "functions/index.html")

def image(request):
    return render(request, "functions/image.html")

def lucky(request):
    # [코드 작성] number 변수에 1부터 100까지의 정수 중 랜덤한 숫자 저장하기
    number = randint(1, 100)

    # 'context' 딕셔너리의 key와 value값으로 HTML에 전달하고 싶은 값을 추가
    context = {
        "number": number,
    }

    # [코드 추가] 'context'값을 HTML로 넘기기
    return render(request, "functions/lucky.html", context)

def birthday(request):
    # [코드 작성] 'datetime'모듈 이용해서 오늘 날짜 가져오기
    today = datetime.date.today()

    # [코드 작성] 'year', 'month', 'day' 변수에 각각 오늘 날짜 정보 저장하기
    year = today.year
    month = today.month
    day = today.day

    # [코드 수정] 내 생일의 월일을 정수로 저장하기
    b_month = 4
    b_day = 17

    # 가장 빠른 생일의 연도 계산
    if (b_month > month):
        b_year = year
    elif (b_month == month) and (b_day >= day):
        b_year = year
    else:
        b_year = year + 1

    # 'datetime'모듈의 'date' 클래스를 이용하여 생일을 datetime 형식으로 만들기
    birthday = datetime.date(b_year, b_month, b_day)

    # 나의 생일까지 남은 요일을 계산
    d_day = birthday - today
    d_day = d_day.days

    context = {
        "year": year,
        "month": month,
        "day": day,
        "b_month": b_month,
        "b_day": b_day,
        "d_day": d_day,
    }

    return render(request, "functions/birthday.html", context)

def ranking(request):
    languages = [
        "Python",
        "C언어",
        "Java",
        "C++",
        "C#",
        "Visual Basic",
        "JavaScript",
        "Assembly",
        "SQL",
        "PHP",
    ]
    
    context = {
        "languages": languages,
    }

    return render(request, "functions/ranking.html", context)

def language(request, name):
    languages = {
        "Python": "웹 애플리케이션, 소프트웨어 개발, 데이터 과학, 기계 학습에 사용되는 프로그래밍 언어",
        "C언어": "1972년 켐 톰프슨과 데니스 리치가 유닉스 운영체제에서 사용하기 위해서 개발한 고급 언어",
        "Java": "1995년 썬 마이크로시스템즈에서 발표한 객체 지향 프로그래밍 언어",
        "C++": "C언어에 여러가지 기능을 추가하여 만든 프로그래밍 언어",
        "C#": "마이크로소프트에서 개발한 객체 지향 프로그래밍 언어",
        "Visual Basic": "마이크로소프트 윈도우용 응용 프로그램을 쉽게 개발하기 위해 만든 프로그래밍 언어",
        "JavaScript": "웹 페이지에서 복잡한 기능을 구현할 수 있도록 하는 프로그래밍 언어",
        "Assembly": "기계어와 일대일 대응이 되는 프로그래밍의 저급 언어",
        "SQL": "관계형 데이터베이스 시스템에서 정보를 저장하고 처리하기 위해 설계된 프로그래밍 언어",
        "PHP": "동적 웹 페이지를 쉽고 빠르게 만들 수 있도록 해주는 프로그래밍 언어",
    }

    # [코드 작성] languages 딕셔너리에서 'functions'앱의 'urls.py'에서 전달받은 인자값 '<str:name>'의 인수값 'name'을 key값으로 하는 value값 가져오기
    detail = languages[name]

    context = {
        "name": name,
        "detail": detail,
    }

    return render(request, "functions/language.html", context)

games/views.py
from django.shortcuts import render, redirect
from random import *

# Create your views here.
# win(승리), draw(무승부), lose(패배) 횟수를 저장하는 전역변수 생성
win = 0
draw = 0
lose = 0

def rsp(request):
    # [미션] 함수에서 전역변수 설정하기
    

    context = {
        "win": win,
        "draw": draw,
        "lose": lose,
    }
    return render(request, "games/rsp.html", context)

def result(request, pick):
    # [미션] 함수에서 전역변수 설정하기
    
    
    rsp = ["가위", "바위", "보"]
    # [미션] 'com' 변수에 'rsp' 리스트의 원소들 중 하나를 랜덤하게 저장하기
    

    # [미션] 내가 선택한 'pick'과 'com' 변수에 저장된 가위바위보 결과를 비교해서 'result' 변수에 결과(승리, 무승부, 패배)를 저장하는 로직 작성하기
    # [미션] win(승리), draw(무승부), lose(패배) 횟수를 가위바위보 결과에 따라 증가시키기










    context = {
        "pick": pick,
        # [미션] 'com'키의 value값을 'com'변수값으로 만들기
        
        "result": result,
        "win": win,
        "draw": draw,
        "lose": lose,
    }

    return render(request, "games/result.html", context)

def reset(request):
    # [미션] 함수에서 전역변수 설정하기
    
    
    # [미션] win(승리), draw(무승부), lose(패배) 횟수를 초기화하기
    

    # 'urls.py'에서 설정한 app_name인 'games'의 url 경로중 별칭이 'rsp'인 경로로 리다이렉트
    return redirect("games:rsp")

functions/templates/functions/birthday.html
{% extends 'base.html' %}

{% block head %}
  <style>
    
  </style>
{% endblock %}

{% block body %}
  <h1>생일 계산기</h1>
  <!-- [코드 추가] 오늘 날짜 보여주기 -->
  <p>오늘은 {{year}}년 {{month}}월 {{day}}일입니다.</p>
  <!-- [코드 추가] Django Template에서 조건문 작성하기 -->
  {% if d_day == day and b_month == month %}
    <p>오늘은 나의 생일입니다.</p>
  {% else %}
    <!-- [코드 추가] 나의 생일 보여주기 -->
    <p>나의 생일은 {{b_month}}월 {{b_day}}일입니다.</p>
    <!-- [코드 추가] 생일까지 남은 날짜 -->
    <p>생일까지 {{d_day}}일 남았습니다.</p>
  {% endif %}
{% endblock %}

functions/templates/functions/image.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <style>
    img {
      width: 200px;
      margin: 20px;
      border: 5px solid gold;
      padding: 20px;
    }
  </style>
{% endblock %}

{% block body %}
  <img src="{% static 'image/walnut.jpg' %}" alt="">
{% endblock %}

functions/templates/functions/index.html
{% extends 'base.html' %}

{% block head %}
  <style>
    li {
      margin: 10px 0;
    }
  </style>
{% endblock %}

{% block body %}
  <h1 style="background-color: pink;">메인 페이지</h1>
  <h2>오늘의 목표</h2>
  <ul>
    <li>Django에서 여러 개의 앱을 사용하는 방법에 대해 알아봅시다.</li>
    <li>View의 기능에 대해 알아봅시다.</li>
    <li>Django의 Template 문법에 대해 알아봅시다.</li>
  </ul>
{% endblock %}

functions/templates/functions/language.html
{% extends 'base.html' %}

{% block head %}
  <style>
    
  </style>
{% endblock %}

{% block body %}
<h1>{{name}}</h1>
<p>
  '{{name}}'은(는) {{detail}}입니다.
</p>
<a href="{% url 'functions:ranking' %}">돌아가기</a>
{% endblock %}

functions/templates/functions/lucky.html
{% extends 'base.html' %}

{% block head %}
  <style>
    
  </style>
{% endblock %}

{% block body %}
  <h1>
    <!-- [코드 추가] View에서 전달한 값 보여주기 -->
    오늘의 행운의 숫자는 {{number}}입니다.
  </h1>
{% endblock %}

functions/templates/functions/ranking.html
{% extends 'base.html' %}

{% block head %}
  <style>
    table {
      border: 2px solid;
    }
    th {
      border: 1px dashed;
      padding: 5px 10px;
    }
    td {
      border: 1px dotted;
      padding: 3px;
      text-align: center;
    }
  </style>
{% endblock %}


{% block body %}
  <table>
    <thead>
      <tr>
        <th>순위</th>
        <th>프로그래밍 언어</th>
      </tr>
    </thead>
    <tbody>
      <!-- [코드 추가] Django Template에서 반복문 작성하기 -->
      {% for language in languages %}
      <tr>
        <!-- [코드 추가] 반복 횟수를 1부터 표시하기 -->
        <td>{{forloop.counter}}위</td>
        <!-- [코드 추가] URL 별칭 사용하기 -->
        <td><a href="{% url 'functions:language' language %}">{{language}}</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

functions/templates/menu.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

{% endblock %}


{% block body %}

{% endblock %}

games/templates/games/result.html
{% extends 'games/rsp.html' %}

{% block rsp %}
  <h1>가위바위보 게임 결과</h1>
  
  <!-- [미션] 가위바위보 중에서 내가 선택한 결과 보여주기 -->
  <p>나는 <b>{{}}</b>를 선택했습니다.</p>

  <!-- [미션] 랜덤하게 선택된 컴퓨터의 결과 보여주기 -->
  <p>컴퓨터는 <b>{{}}</b>를 선택했습니다.</p>

  <h2 style="color: red;">
    {% if result == "승리" %}
      내가 이겼습니다.
    {% elif result == "무승부" %}
      비겼습니다.
    {% else %}
      컴퓨터가 이겼습니다.
    {% endif %}
  </h2>
  
{% endblock %}

games/templates/games/rsp.html
{% extends 'base.html' %}

{% block head %}
  <style>
    .rsp {
      padding: 10px 0;
    }
    .rsp a {
      margin: 0 2px;
      padding: 10px 20px;
      text-decoration: none;
      border: 1px solid;
      border-radius: 15px;
    }
    .rsp a:hover {
      background-color: rgb(225, 225, 255);
    }
    .count {
      width: 25%;
      border: 1px solid;
      padding: 10px;
      margin: 10px 0;
    }
  </style>
{% endblock %}

{% block body %}

  {% block rsp %}
    <h1>가위바위보 게임</h1>

  {% endblock %}
  <div class="count">
    <p>승리 횟수 : {{win}}회</p>
    <p>무승부 횟수 : {{draw}}회</p>
    <p>패배 횟수 : {{lose}}회</p>

    <a href="{% url 'games:reset' %}">초기화</a>
  </div>

  <h3>선택해주세요~</h3>
  <div class="rsp">
    <a href="{% url 'games:result' '가위' %}">가위</a>
    <a href="{% url 'games:result' '바위' %}">바위</a>
    <a href="{% url 'games:result' '보' %}">보</a>
  </div>
  
{% endblock %}

intro/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- 내부 스타일 시트 적용 -->
  <style>
    .header {
      margin: 15px;
    }

    .header a {
      display: inline-block;
      border: 1px solid;
      border-radius: 15px;
      padding: 5px 10px;
      margin: 3px 0;
      text-decoration: none;
    }

    .header a:nth-of-type(1) {
      color: red;
      background-color: rgb(255, 230, 230);
    }

    .header a:nth-of-type(2) {
      color: OrangeRed;
      background-color: rgb(255, 233, 226);
    }

    .header a:nth-of-type(3) {
      color: orange;
      background-color: rgb(255, 245, 227);
    }

    .header a:nth-of-type(4) {
      color: green;
      background-color: rgb(229, 255, 229);
    }

    .header a:nth-of-type(5) {
      color: blue;
      background-color: rgb(228, 228, 255);
    }
    
    .header a:nth-of-type(6) {
      color: purple;
      background-color: rgb(255, 232, 255);
    }
  </style>
  <!-- 외부 스타일 시트 적용 -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <!-- 공통으로 사용하는 부분 -->
  <div class="header">
    <!-- URL 별칭 사용하기 -->
    <a href="{% url 'functions:index' %}">홈</a>
    <a href="{% url 'functions:image' %}">이미지</a>
    <a href="{% url 'functions:lucky' %}">행운의 숫자</a>
    <a href="{% url 'functions:birthday' %}">생일</a>
    <a href="{% url 'functions:ranking' %}">프로그래밍 언어 순위</a>
    <!-- [미션] 가위바위보 게임으로 이동하는 a태그 만들기 -->
    
  </div>

  {% block body %}
  {% endblock %}
</body>
</html>